### ISSUE TITLE
deprecated tags in demo theme

### ISSUE THREAD

**Issue by markdalderup** [zenphoto/demo-theme#1]
in the following files the deprecated tag getAlbumLinkURL() is still used

demo-theme-master\demo-theme-master\demo_theme\album.php
demo-theme-master\demo-theme-master\demo_theme\favorites.php
demo-theme-master\demo-theme-master\demo_theme\index.php
demo-theme-master\demo-theme-master\demo_theme\search.php
demo-theme-master\demo-theme-master\demo_theme-zenpage-cms-extras-files\search.ph

this should be getAlbumURL() 

Also if you look in https://docs.zenphoto.org/1.5.x/ for the tag getAlbumLinkURL you cannot find it.
its not listed in the deprecated tags

**Comment by acrylian** [comment]
Thanks, these deprecations have indeed been removed several versions ago. Also fixed usages of the equally outdates `getImageLinkURL()`.
